// Structured-data @graph ported verbatim from the old index.html <head>.
export const homeJsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "https://pacificedge.ai/#organization",
      name: "Pacific Edge AI",
      alternateName: ["PacificEdge.ai", "Pacific Edge AI Consulting"],
      url: "https://pacificedge.ai/",
      logo: { "@type": "ImageObject", url: "https://pacificedge.ai/apple-touch-icon.png", width: 180, height: 180 },
      image: "https://pacificedge.ai/og-image.png",
      description:
        "AI consulting in Vancouver, BC. Pacific Edge AI builds custom AI automation for hospitality, wellness, professional services, and retail businesses across the Lower Mainland.",
      email: "hello@pacificedge.ai",
      address: { "@type": "PostalAddress", addressLocality: "Vancouver", addressRegion: "BC", addressCountry: "CA" },
      areaServed: [
        { "@type": "City", name: "Vancouver" },
        { "@type": "City", name: "Burnaby" },
        { "@type": "City", name: "Richmond" },
        { "@type": "City", name: "Surrey" },
        { "@type": "City", name: "North Vancouver" },
        { "@type": "AdministrativeArea", name: "British Columbia" },
        { "@type": "AdministrativeArea", name: "Lower Mainland" },
      ],
      contactPoint: { "@type": "ContactPoint", email: "hello@pacificedge.ai", contactType: "Sales", areaServed: "CA", availableLanguage: "English" },
      knowsAbout: [
        "AI consulting", "AI consulting Vancouver", "AI automation", "Custom AI workflows",
        "Business process automation", "Missed call auto-responder", "AI review management",
        "Customer follow-up automation", "Social content automation", "AI for small business",
      ],
      sameAs: ["https://cal.com/pacificedge"],
    },
    {
      "@type": "ProfessionalService",
      "@id": "https://pacificedge.ai/#localbusiness",
      name: "Pacific Edge AI",
      image: "https://pacificedge.ai/og-image.png",
      url: "https://pacificedge.ai/",
      email: "hello@pacificedge.ai",
      priceRange: "$$",
      description:
        "AI consulting Vancouver. Pacific Edge AI builds custom AI automation for hospitality, wellness, professional services, and retail businesses across Vancouver and the Lower Mainland.",
      address: { "@type": "PostalAddress", addressLocality: "Vancouver", addressRegion: "BC", addressCountry: "CA" },
      geo: { "@type": "GeoCoordinates", latitude: 49.2827, longitude: -123.1207 },
      areaServed: [
        { "@type": "City", name: "Vancouver" },
        { "@type": "AdministrativeArea", name: "British Columbia" },
        { "@type": "AdministrativeArea", name: "Lower Mainland" },
      ],
      serviceType: ["AI Consulting", "AI Automation", "Business Process Automation", "Custom Software Development", "Marketing Technology Consulting"],
      hasOfferCatalog: {
        "@type": "OfferCatalog",
        name: "AI Consulting Services",
        itemListElement: [
          { "@type": "Offer", itemOffered: { "@type": "Service", name: "Capture Every Lead", serviceType: "AI Lead Recovery", description: "Missed-call text-back, after-hours coverage, and automated follow-up, so no lead slips through the cracks." } },
          { "@type": "Offer", itemOffered: { "@type": "Service", name: "Fill Every Booking", serviceType: "AI Booking Recovery", description: "Cancellations refilled from your waitlist, no-shows cut with smart reminders, and every open slot put back to work." } },
          { "@type": "Offer", itemOffered: { "@type": "Service", name: "Own Your Reputation", serviceType: "AI Review Management", description: "On-brand replies to every Google review in a tap, plus more 5-star reviews from your happiest customers." } },
          { "@type": "Offer", itemOffered: { "@type": "Service", name: "Custom AI Software", serviceType: "Custom Software Development", description: "Custom AI software, workflows, and dashboards built around how each business actually runs and integrated with the tools they already use." } },
        ],
      },
      knowsAbout: ["AI consulting Vancouver", "AI automation for small business", "Custom AI workflows", "Missed call recovery", "AI review management", "Customer follow-up automation", "Process automation"],
    },
    {
      "@type": "WebSite",
      "@id": "https://pacificedge.ai/#website",
      url: "https://pacificedge.ai/",
      name: "Pacific Edge AI",
      description: "AI consulting in Vancouver, BC. Custom AI automation for local business.",
      publisher: { "@id": "https://pacificedge.ai/#organization" },
      inLanguage: "en-CA",
    },
    {
      "@type": "Service",
      "@id": "https://pacificedge.ai/#service-ai-consulting",
      name: "AI Consulting Vancouver",
      serviceType: "AI Consulting",
      provider: { "@id": "https://pacificedge.ai/#organization" },
      areaServed: [
        { "@type": "City", name: "Vancouver" },
        { "@type": "AdministrativeArea", name: "British Columbia" },
      ],
      description:
        "Hands-on AI consulting for Vancouver-area small businesses. We assess where your time and money are leaking, design custom AI workflows, build and deploy them, then optimize over time.",
      audience: { "@type": "BusinessAudience", audienceType: "Small and medium-sized businesses", geographicArea: { "@type": "AdministrativeArea", name: "British Columbia" } },
    },
    {
      "@type": "FAQPage",
      "@id": "https://pacificedge.ai/#faq",
      mainEntity: [
        { "@type": "Question", name: "Do I need to be tech-savvy?", acceptedAnswer: { "@type": "Answer", text: "Not even a little. If you can use a smartphone, you can use what we build. We handle all the technical work and walk you through everything in plain English. Our whole business exists because most AI tools are built for developers - we translate that into something anyone can use." } },
        { "@type": "Question", name: "How long does setup take?", acceptedAnswer: { "@type": "Answer", text: "Most clients have a working prototype within the first week. Full deployment and training typically wraps up in two to three weeks depending on complexity. You'll see real results before most agencies finish their discovery phase." } },
        { "@type": "Question", name: "How much does it cost?", acceptedAnswer: { "@type": "Answer", text: "Every business is different - a single-location salon has very different needs than a multi-site restaurant group. Our solutions are custom-built around your specific workflows, team size, and goals, so pricing reflects exactly what you need and nothing you don't. Book a free discovery call and we'll put together a transparent quote tailored to your business." } },
        { "@type": "Question", name: "What if I want to cancel?", acceptedAnswer: { "@type": "Answer", text: "Your first month is on us, so you can make sure Janice is the right fit before anything kicks in. From there, engagements run for an initial 6 months, long enough to build, deploy, train your team, and prove real ROI. Pricing is transparent and agreed upfront, with no hidden fees and no surprise renewals. After that you can renew month-to-month, scale up, or part ways with everything we've built fully documented for handover." } },
        { "@type": "Question", name: "Will this actually work for my industry?", acceptedAnswer: { "@type": "Answer", text: "If your business relies on appointments, customer communication, or online reviews, the answer is almost certainly yes. We've designed our workflows specifically for hospitality, wellness, trades, and retail - the industries where these automations have the highest impact." } },
        { "@type": "Question", name: "Will my data be safe?", acceptedAnswer: { "@type": "Answer", text: "Absolutely. Security isn't an afterthought - it's built into everything we do. All data is encrypted, access is restricted to only what's needed, and we never share your information with third parties. Your business data stays your business data, period." } },
        { "@type": "Question", name: "What happens on the discovery call?", acceptedAnswer: { "@type": "Answer", text: "Fifteen minutes. We learn about your business, identify where you're losing time or money, and tell you exactly which automations would make the biggest difference. No pitch deck, no pressure. If we're not the right fit, we'll tell you that too." } },
      ],
    },
    {
      "@type": "HowTo",
      "@id": "https://pacificedge.ai/#process",
      name: "How AI consulting works at Pacific Edge AI",
      description: "Our 5-step process for delivering AI consulting and automation to Vancouver small businesses.",
      totalTime: "P21D",
      step: [
        { "@type": "HowToStep", position: 1, name: "Discovery Call", text: "15 minutes. We learn about your business, find where you're bleeding time and money, and identify the highest-impact automations. No sales pitch. Just clarity." },
        { "@type": "HowToStep", position: 2, name: "Deep-Dive Session", text: "A focused 60-minute session where we map out your entire workflow, pinpoint the bottlenecks costing you the most time and money, and identify exactly which automations will move the needle for your business." },
        { "@type": "HowToStep", position: 3, name: "Custom Build", text: "We design and build your AI workflows using battle-tested tools. You see a working prototype within the first week, not a slide deck, real software." },
        { "@type": "HowToStep", position: 4, name: "Launch & Train", text: "We deploy everything, walk your team through it in plain English, and make sure you're comfortable before we step back. No orphaned systems." },
        { "@type": "HowToStep", position: 5, name: "Optimize & Support", text: "Ongoing monitoring and tweaking. As your business grows, we scale your automations with you. You focus on running the business. We keep the systems humming." },
      ],
    },
  ],
}
