// Structured-data @graph ported verbatim from the old index.html <head>.
export const homeJsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "https://pacificedge.ai/#organization",
      name: "Pacific Edge AI",
      alternateName: ["PacificEdge.ai", "Pacific Edge AI Consulting"],
      url: "https://pacificedge.ai/",
      logo: { "@type": "ImageObject", url: "https://pacificedge.ai/apple-touch-icon.png", width: 180, height: 180 },
      image: "https://pacificedge.ai/og-image.png",
      description:
        "AI consulting in Vancouver, BC. Pacific Edge AI builds custom AI automation for hospitality, wellness, professional services, and retail businesses across the Lower Mainland.",
      email: "hello@pacificedge.ai",
      address: { "@type": "PostalAddress", addressLocality: "Vancouver", addressRegion: "BC", addressCountry: "CA" },
      areaServed: [
        { "@type": "City", name: "Vancouver" },
        { "@type": "City", name: "Burnaby" },
        { "@type": "City", name: "Richmond" },
        { "@type": "City", name: "Surrey" },
        { "@type": "City", name: "North Vancouver" },
        { "@type": "AdministrativeArea", name: "British Columbia" },
        { "@type": "AdministrativeArea", name: "Lower Mainland" },
      ],
      contactPoint: { "@type": "ContactPoint", email: "hello@pacificedge.ai", contactType: "Sales", areaServed: "CA", availableLanguage: "English" },
      knowsAbout: [
        "AI consulting", "AI consulting Vancouver", "AI automation", "Custom AI workflows",
        "Business process automation", "Missed call auto-responder", "AI review management",
        "Customer follow-up automation", "Social content automation", "AI for small business",
      ],
      sameAs: ["https://cal.com/pacificedge"],
    },
    {
      "@type": "ProfessionalService",
      "@id": "https://pacificedge.ai/#localbusiness",
      name: "Pacific Edge AI",
      image: "https://pacificedge.ai/og-image.png",
      url: "https://pacificedge.ai/",
      email: "hello@pacificedge.ai",
      priceRange: "$$",
      description:
        "AI consulting Vancouver. Pacific Edge AI builds custom AI automation for hospitality, wellness, professional services, and retail businesses across Vancouver and the Lower Mainland.",
      address: { "@type": "PostalAddress", addressLocality: "Vancouver", addressRegion: "BC", addressCountry: "CA" },
      geo: { "@type": "GeoCoordinates", latitude: 49.2827, longitude: -123.1207 },
      areaServed: [
        { "@type": "City", name: "Vancouver" },
        { "@type": "AdministrativeArea", name: "British Columbia" },
        { "@type": "AdministrativeArea", name: "Lower Mainland" },
      ],
      serviceType: ["AI Consulting", "AI Automation", "Business Process Automation", "Custom Software Development", "Marketing Technology Consulting"],
      hasOfferCatalog: {
        "@type": "OfferCatalog",
        name: "AI Consulting Services",
        itemListElement: [
          { "@type": "Offer", itemOffered: { "@type": "Service", name: "Capture Every Lead", serviceType: "AI Lead Recovery", description: "Missed-call text-back, after-hours coverage, and automated follow-up, so no lead slips through the cracks." } },
          { "@type": "Offer", itemOffered: { "@type": "Service", name: "Fill Every Booking", serviceType: "AI Booking Recovery", description: "Cancellations refilled from your waitlist, no-shows cut with smart reminders, and every open slot put back to work." } },
          { "@type": "Offer", itemOffered: { "@type": "Service", name: "Own Your Reputation", serviceType: "AI Review Management", description: "On-brand replies to every Google review in a tap, plus more 5-star reviews from your happiest customers." } },
          { "@type": "Offer", itemOffered: { "@type": "Service", name: "Custom AI Software", serviceType: "Custom Software Development", description: "Custom AI software, workflows, and dashboards built around how each business actually runs and integrated with the tools they already use." } },
        ],
      },
      knowsAbout: ["AI consulting Vancouver", "AI automation for small business", "Custom AI workflows", "Missed call recovery", "AI review management", "Customer follow-up automation", "Process automation"],
    },
    {
      "@type": "WebSite",
      "@id": "https://pacificedge.ai/#website",
      url: "https://pacificedge.ai/",
      name: "Pacific Edge AI",
      description: "AI consulting in Vancouver, BC. Custom AI automation for local business.",
      publisher: { "@id": "https://pacificedge.ai/#organization" },
      inLanguage: "en-CA",
    },
    {
      "@type": "Service",
      "@id": "https://pacificedge.ai/#service-ai-consulting",
      name: "AI Consulting Vancouver",
      serviceType: "AI Consulting",
      provider: { "@id": "https://pacificedge.ai/#organization" },
      areaServed: [
        { "@type": "City", name: "Vancouver" },
        { "@type": "AdministrativeArea", name: "British Columbia" },
      ],
      description:
        "Hands-on AI consulting for Vancouver-area small businesses. We assess where your time and money are leaking, design custom AI workflows, build and deploy them, then optimize over time.",
      audience: { "@type": "BusinessAudience", audienceType: "Small and medium-sized businesses", geographicArea: { "@type": "AdministrativeArea", name: "British Columbia" } },
    },
    {
      "@type": "HowTo",
      "@id": "https://pacificedge.ai/how-it-works#process",
      name: "How AI consulting works at Pacific Edge AI",
      description: "Our 5-step process for delivering AI consulting and automation to Vancouver small businesses.",
      totalTime: "P21D",
      step: [
        { "@type": "HowToStep", position: 1, name: "Discovery Call", text: "15 minutes. We learn about your business, find where you're bleeding time and money, and identify the highest-impact automations. No sales pitch. Just clarity." },
        { "@type": "HowToStep", position: 2, name: "Deep-Dive Session", text: "A focused 60-minute session where we map out your entire workflow, pinpoint the bottlenecks costing you the most time and money, and identify exactly which automations will move the needle for your business." },
        { "@type": "HowToStep", position: 3, name: "Custom Build", text: "We design and build your AI workflows using battle-tested tools. You see a working prototype within the first week, not a slide deck, real software." },
        { "@type": "HowToStep", position: 4, name: "Launch & Train", text: "We deploy everything, walk your team through it in plain English, and make sure you're comfortable before we step back. No orphaned systems." },
        { "@type": "HowToStep", position: 5, name: "Optimize & Support", text: "Ongoing monitoring and tweaking. As your business grows, we scale your automations with you. You focus on running the business. We keep the systems humming." },
      ],
    },
  ],
}
