import type { ClientSession } from "@/lib/auth/demo-session"
import type { ClientDashboardData, DashboardIndustry } from "./types"

const BASE: Record<Exclude<DashboardIndustry, "all">, ClientDashboardData> = {
  restaurants: {
    business: "Wildfire Kitchen",
    email: "demo@wildfirekitchen.ca",
    subtitle: "Here is everything happening across the restaurant right now.",
    chips: [
      ["Covers tonight", "86"],
      ["Recovered by AI", "14"],
      ["Avg response", "0:21"],
      ["Live now", "1"],
    ],
    live: {
      name: "(604) 555-0148",
      sub: "New caller · Yaletown · table request",
      line: '"...a table for 4 tonight around 7:30?"',
    },
    calls: [
      {
        icon: "phone",
        who: "(604) 555-0148",
        sub: "Table request · 2:14 PM",
        pill: "Booked · +$220",
        status: "ok",
        detail: "Wanted a table for 4 tonight. Platform offered 7:45 and booked it.",
      },
      {
        icon: "refill",
        who: "8:00 PM cancellation",
        sub: "Refilled from waitlist · 1:30 PM",
        pill: "Refilled",
        status: "ok",
        detail: "A party cancelled. Platform offered the slot to the waitlist and rebooked in 7 min.",
      },
      {
        icon: "sms",
        who: "(778) 555-0192",
        sub: "Missed · texted back · 1:02 PM",
        pill: "Booked",
        status: "ok",
        detail: "Booked a table for 2 on Friday.",
      },
      {
        icon: "catering",
        who: "Catering inquiry",
        sub: "Large party · 11:10 AM",
        pill: "Quote sent",
        status: "warn",
        detail: "30-person event. Platform captured details and sent a quote.",
      },
    ],
    convos: [
      {
        id: "r1",
        name: "Sarah M.",
        channel: "SMS",
        avatar: "S",
        last: "Perfect, see you at 7:15!",
        time: "2m",
        status: "Booked",
        statusClass: "ok",
        messages: [
          { from: "customer", text: "Table for 4 tonight around 7?" },
          { from: "assistant", text: "We have 7:15 for 4, book it?", meta: "Auto · 19s" },
          { from: "customer", text: "Yes please" },
          { from: "assistant", text: "Booked for 7:15, party of 4!" },
          { from: "customer", text: "Perfect, see you at 7:15!" },
        ],
      },
      {
        id: "r2",
        name: "(604) 555-0192",
        channel: "SMS",
        avatar: "#",
        last: "Yes please, book it",
        time: "1h",
        status: "Booked",
        statusClass: "ok",
        messages: [
          { from: "assistant", text: "Sorry we missed your call. How can we help?" },
          { from: "customer", text: "Table for 2 Friday" },
          { from: "assistant", text: "Friday 6:30 for 2, book it?" },
          { from: "customer", text: "Yes please, book it" },
          { from: "assistant", text: "Done! Friday 6:30, party of 2." },
        ],
      },
      {
        id: "r3",
        name: "Mike D.",
        channel: "Instagram",
        avatar: "M",
        last: "Do you do private events?",
        time: "4h",
        status: "Needs you",
        statusClass: "warn",
        messages: [
          { from: "customer", text: "Do you do private events?" },
          {
            from: "assistant",
            text: "We do! For 20+ our manager tailors a menu. I have flagged this for the team.",
            meta: "Auto · 22s",
          },
        ],
      },
    ],
    schedLabel: "Reservations",
    schedTitle: "Reservations this week",
    schedule: [
      [
        ["5:00 PM", "Patel", "Party of 2", "Confirmed", "ok"],
        ["7:15 PM", "Sarah M.", "Party of 4", "Confirmed", "ok"],
        ["8:00 PM", "From waitlist", "Party of 4 · refilled", "Refilled", "ok"],
        ["8:30 PM", "Chen", "Party of 6", "Pending", "warn"],
      ],
      [
        ["6:00 PM", "Okafor", "Party of 5", "Confirmed", "ok"],
        ["7:30 PM", "Lopez", "Party of 8", "Confirmed", "ok"],
      ],
      [["6:30 PM", "Tran", "Party of 2", "Confirmed", "ok"]],
      [],
      [
        ["5:30 PM", "Singh", "Party of 6", "Confirmed", "ok"],
        ["7:00 PM", "Beaumont", "Party of 4", "Confirmed", "ok"],
        ["9:00 PM", "Diaz", "Party of 2", "Confirmed", "ok"],
      ],
      [["6:00 PM", "Private event", "30 guests · deposit paid", "Confirmed", "ok"]],
      [],
    ],
    extraLabel: "Waitlist",
    extraTitle: "Tonight's waitlist",
    extra: [
      ["waitlist", "Reyes · party of 2", "Waiting since 6:40 PM", "Next up", "ok"],
      ["waitlist", "Kim · party of 4", "Offered the 8 PM cancellation", "Offered", "warn"],
      ["waitlist", "Patterson · party of 3", "Texted when a table frees", "Waiting", "ok"],
      ["waitlist", "Nguyen · party of 2", "Seated from waitlist", "Seated", "ok"],
    ],
    reviews: [
      {
        avatar: "S",
        name: "Sarah K.",
        stars: 5,
        channel: "Google",
        when: "2h ago",
        text: "Best dinner we have had in Vancouver. The tasting menu was incredible.",
        draft: "Thank you, Sarah! Our chef will be thrilled. We cannot wait to cook for you again.",
      },
      {
        avatar: "D",
        name: "Dishan P.",
        stars: 4,
        channel: "Google",
        when: "1d ago",
        text: "Lovely food, table a few minutes late but worth it.",
        draft: "Thanks Dishan! We are tightening our timing and hope to seat you right on time next visit.",
      },
      {
        avatar: "A",
        name: "Amara O.",
        stars: 5,
        channel: "Yelp",
        when: "3d ago",
        text: "Booked last minute by text and they fit us in. Amazing.",
        draft: "Thank you, Amara! Fitting you in was our pleasure. See you next time!",
      },
    ],
  },
  salons: {
    business: "Luxe Hair Studio",
    email: "demo@luxehair.ca",
    subtitle: "Here is everything happening across the salon right now.",
    chips: [
      ["Booked today", "24"],
      ["Rebooking rate", "68%"],
      ["Avg response", "0:28"],
      ["Live now", "1"],
    ],
    live: {
      name: "@luxe_client",
      sub: "Instagram DM · balayage",
      line: '"...any openings for balayage this weekend?"',
    },
    calls: [
      {
        icon: "dm",
        who: "Balayage · Instagram",
        sub: "DM booked · 2:14 PM",
        pill: "Booked",
        status: "ok",
        detail: "Asked about balayage. Platform offered Saturday 1:30 and booked it.",
      },
      {
        icon: "refill",
        who: "2:00 PM cancellation",
        sub: "Refilled · 1:30 PM",
        pill: "Refilled",
        status: "ok",
        detail: "A client cancelled. Platform offered the chair to the waitlist and rebooked in 9 min.",
      },
      {
        icon: "phone",
        who: "(604) 555-0080",
        sub: "Inbound · 11:15 AM",
        pill: "Booked",
        status: "ok",
        detail: "Booked a men's cut for Thursday.",
      },
      {
        icon: "rebook",
        who: "Priya · rebooking",
        sub: "6-week reminder · 9:40 AM",
        pill: "Rebooked",
        status: "ok",
        detail: "Reminded Priya she was due. She rebooked on the spot.",
      },
    ],
    convos: [
      {
        id: "s1",
        name: "Priya K.",
        channel: "Instagram",
        avatar: "P",
        last: "Yes book me in!",
        time: "5m",
        status: "Booked",
        statusClass: "ok",
        messages: [
          { from: "customer", text: "Any openings for balayage this weekend?" },
          { from: "assistant", text: "Saturday 1:30 with Alexa, ~2.5 hrs. Book it?", meta: "Auto · 22s" },
          { from: "customer", text: "Yes book me in!" },
          { from: "assistant", text: "Booked! Saturday 1:30 with Alexa." },
        ],
      },
      {
        id: "s2",
        name: "Mara L.",
        channel: "SMS",
        avatar: "M",
        last: "C",
        time: "1h",
        status: "Confirmed",
        statusClass: "ok",
        messages: [
          { from: "assistant", text: "Reminder: colour & cut tomorrow 11 AM. Reply C." },
          { from: "customer", text: "C" },
          { from: "assistant", text: "Confirmed! See you at 11." },
        ],
      },
      {
        id: "s3",
        name: "(604) 555-0231",
        channel: "SMS",
        avatar: "#",
        last: "How much for highlights?",
        time: "3h",
        status: "AI replied",
        statusClass: "ok",
        messages: [
          { from: "customer", text: "How much for partial highlights?" },
          { from: "assistant", text: "Partial highlights start at $160. Want me to find a time?", meta: "Auto · 18s" },
        ],
      },
    ],
    schedLabel: "Appointments",
    schedTitle: "Appointments this week",
    schedule: [
      [
        ["11:00 AM", "Mara L.", "Colour & cut · 90 min", "Confirmed", "ok"],
        ["2:00 PM", "From waitlist", "Cut & style · refilled", "Refilled", "ok"],
        ["4:30 PM", "Devon R.", "Men's cut · 30 min", "Confirmed", "ok"],
      ],
      [
        ["1:30 PM", "Priya K.", "Balayage · 2.5 hr", "Confirmed", "ok"],
        ["5:00 PM", "Sam W.", "Consultation", "Pending", "warn"],
      ],
      [
        ["10:00 AM", "Bianca", "Cut · 45 min", "Confirmed", "ok"],
        ["1:00 PM", "Theo", "Beard trim", "Confirmed", "ok"],
      ],
      [],
      [
        ["11:30 AM", "Hannah", "Colour · 2 hr", "Confirmed", "ok"],
        ["3:30 PM", "Aisha", "Balayage · 2.5 hr", "Confirmed", "ok"],
      ],
      [["12:00 PM", "Rae", "Updo · bridal trial", "Confirmed", "ok"]],
      [],
    ],
    extraLabel: "Rebookings",
    extraTitle: "Clients due to rebook",
    extra: [
      ["rebook", "Priya K.", "Due for a 6-week trim", "Reminder sent", "ok"],
      ["rebook", "Jordan F.", "8 weeks since last colour", "Nudge queued", "warn"],
      ["rebook", "Nadia S.", "Lapsed 90 days", "Win-back sent", "ok"],
      ["review", "Mara L.", "Loved her cut", "Review request sent", "ok"],
    ],
    reviews: [
      {
        avatar: "P",
        name: "Priya K.",
        stars: 5,
        channel: "Google",
        when: "3h ago",
        text: "Alexa did the most beautiful balayage. Obsessed!",
        draft: "Thank you, Priya! Alexa will be so happy. See you at your next appointment!",
      },
      {
        avatar: "J",
        name: "Jordan F.",
        stars: 5,
        channel: "Google",
        when: "2d ago",
        text: "Booking over Instagram was instant. Loved my cut.",
        draft: "Thanks, Jordan! Easy booking is what we love to hear.",
      },
      {
        avatar: "N",
        name: "Nadia S.",
        stars: 4,
        channel: "Yelp",
        when: "4d ago",
        text: "Great colour, ran a little behind but happy.",
        draft: "Thank you, Nadia! We are working on our timing and appreciate your patience.",
      },
    ],
  },
  trades: {
    business: "Coastal Plumbing & Heating",
    email: "demo@coastalplumbing.ca",
    subtitle: "Here is everything happening across the business right now.",
    chips: [
      ["Jobs booked", "11"],
      ["Quotes won", "9"],
      ["Avg response", "0:18"],
      ["Live now", "1"],
    ],
    live: {
      name: "(604) 555-0148",
      sub: "New caller · water heater leak",
      line: '"...my water heater is leaking, can someone come today?"',
    },
    calls: [
      {
        icon: "phone",
        who: "(604) 555-0148",
        sub: "Water heater leak · 2:14 PM",
        pill: "Job booked",
        status: "ok",
        detail: "Urgent leak. Platform triaged it and booked a tech for 4 PM today.",
      },
      {
        icon: "quote",
        who: "Panel upgrade quote",
        sub: "Followed up · 1:02 PM",
        pill: "Accepted",
        status: "ok",
        detail: "Platform followed up on a $2,400 quote. Customer accepted.",
      },
      {
        icon: "sms",
        who: "(778) 555-0192",
        sub: "After-hours · texted back · 9:42 PM",
        pill: "Booked",
        status: "ok",
        detail: "After-hours call texted back. Booked a morning service call.",
      },
      {
        icon: "quote",
        who: "Furnace install quote",
        sub: "Reminder sent · 11:10 AM",
        pill: "Following up",
        status: "warn",
        detail: "$5,800 quote, awaiting reply.",
      },
    ],
    convos: [
      {
        id: "t1",
        name: "(604) 555-0148",
        channel: "SMS",
        avatar: "#",
        last: "Yes that works, thank you",
        time: "4m",
        status: "Booked",
        statusClass: "ok",
        messages: [
          { from: "customer", text: "Water heater is leaking, can someone come today?" },
          {
            from: "assistant",
            text: "Sorry to hear that! Tech can come 4-6 PM today. Lock it in?",
            meta: "Auto · 16s",
          },
          { from: "customer", text: "Yes that works, thank you" },
          { from: "assistant", text: "Booked! Mike will text when on the way. Address?" },
        ],
      },
      {
        id: "t2",
        name: "Dan R.",
        channel: "SMS",
        avatar: "D",
        last: "Sounds good, go ahead",
        time: "1h",
        status: "Accepted",
        statusClass: "ok",
        messages: [
          { from: "assistant", text: "Following up on your panel upgrade quote ($2,400). Questions?" },
          { from: "customer", text: "Sounds good, go ahead" },
          { from: "assistant", text: "Great! Booked Tuesday 9 AM." },
        ],
      },
      {
        id: "t3",
        name: "(236) 555-0177",
        channel: "SMS",
        avatar: "#",
        last: "How soon can you come?",
        time: "3h",
        status: "AI replied",
        statusClass: "ok",
        messages: [
          { from: "customer", text: "How soon for a clogged drain?" },
          { from: "assistant", text: "We have tomorrow 8 AM. Book it?", meta: "Auto · 20s" },
        ],
      },
    ],
    schedLabel: "Jobs",
    schedTitle: "Jobs this week",
    schedule: [
      [
        ["4:00 PM", "Burnaby", "Water heater · service call", "Confirmed", "ok"],
        ["Eve", "On-call", "Emergency window", "Standby", "warn"],
      ],
      [
        ["8:00 AM", "Surrey", "Drain repair", "Confirmed", "ok"],
        ["9:00 AM", "Dan R.", "Panel upgrade", "Confirmed", "ok"],
        ["1:00 PM", "Richmond", "Furnace tune-up", "Confirmed", "ok"],
      ],
      [["10:00 AM", "New West", "Leak inspection", "Confirmed", "ok"]],
      [],
      [
        ["8:30 AM", "Coquitlam", "Water heater install", "Confirmed", "ok"],
        ["2:00 PM", "Langley", "Faucet replacement", "Confirmed", "ok"],
      ],
      [],
      [["9:00 AM", "On-call", "Weekend emergencies", "Standby", "ok"]],
    ],
    extraLabel: "Quotes",
    extraTitle: "Outstanding quotes",
    extra: [
      ["quote", "Furnace install · $5,800", "Sent 2 days ago", "Following up", "warn"],
      ["quote", "Bathroom reno · $9,200", "Awaiting homeowner", "Day 1", "warn"],
      ["quote", "Panel upgrade · $2,400", "Customer said yes", "Accepted", "ok"],
      ["quote", "Drain camera · $480", "Quote viewed", "Reminder sent", "ok"],
    ],
    reviews: [
      {
        avatar: "D",
        name: "Dan R.",
        stars: 5,
        channel: "Google",
        when: "4h ago",
        text: "Called in a panic about a leak, they texted right back and came same day. Lifesavers.",
        draft: "Thank you, Dan! Same-day help is exactly what we aim for. Glad we sorted it fast.",
      },
      {
        avatar: "L",
        name: "Linda M.",
        stars: 5,
        channel: "Google",
        when: "2d ago",
        text: "Clear quote, on time, tidy work. Will use again.",
        draft: "Thanks, Linda! Clear quotes and tidy work are our standard. Here whenever you need us.",
      },
      {
        avatar: "R",
        name: "Raj P.",
        stars: 4,
        channel: "Google",
        when: "5d ago",
        text: "Good job on the furnace, tricky to schedule at first.",
        draft: "Thank you, Raj! We have smoothed out our scheduling since. Appreciate your patience.",
      },
    ],
  },
  retail: {
    business: "North Arm Goods",
    email: "demo@northarmgoods.ca",
    subtitle: "Here is everything happening across the shop right now.",
    chips: [
      ["Orders today", "27"],
      ["Brought back", "8"],
      ["Avg response", "0:30"],
      ["Live now", "1"],
    ],
    live: {
      name: "(604) 555-0148",
      sub: "Live text · stock question",
      line: '"...still have the olive linen jacket in a medium?"',
    },
    calls: [
      {
        icon: "sms",
        who: "Olive linen jacket",
        sub: "Held at counter · 1:20 PM",
        pill: "Held",
        status: "ok",
        detail: "Asked about stock. Platform confirmed and held it at the counter.",
      },
      {
        icon: "sms",
        who: "Open today?",
        sub: "Answered · 12:05 PM",
        pill: "Replied",
        status: "ok",
        detail: "Hours answered instantly with directions.",
      },
      {
        icon: "winback",
        who: "Lapsed customer",
        sub: "Win-back sent · 10:30 AM",
        pill: "Returned",
        status: "ok",
        detail: "No visit in 60 days. Platform sent a win-back and they came in.",
      },
      {
        icon: "campaign",
        who: "Fall drop",
        sub: "Campaign · 9:00 AM",
        pill: "38 redeemed",
        status: "ok",
        detail: "New-arrivals text sent. 38 redemptions so far.",
      },
    ],
    convos: [
      {
        id: "rt1",
        name: "(604) 555-0148",
        channel: "SMS",
        avatar: "#",
        last: "Amazing, thank you!",
        time: "6m",
        status: "Held",
        statusClass: "ok",
        messages: [
          { from: "customer", text: "Still have the olive linen jacket in a medium?" },
          { from: "assistant", text: "We do! Hold it at the counter til tomorrow?", meta: "Auto · 18s" },
          { from: "customer", text: "Yes please" },
          { from: "assistant", text: "Holding 1 olive linen (M) til 6 PM tomorrow." },
          { from: "customer", text: "Amazing, thank you!" },
        ],
      },
      {
        id: "rt2",
        name: "Erin C.",
        channel: "Instagram",
        avatar: "E",
        last: "Perfect, see you Sat",
        time: "2h",
        status: "Booked",
        statusClass: "ok",
        messages: [
          { from: "customer", text: "Do you do personal shopping?" },
          { from: "assistant", text: "We do! Saturday 11 AM with our stylist. Book it?", meta: "Auto · 21s" },
          { from: "customer", text: "Perfect, see you Sat" },
        ],
      },
      {
        id: "rt3",
        name: "(778) 555-0233",
        channel: "SMS",
        avatar: "#",
        last: "Hours Sunday?",
        time: "4h",
        status: "AI replied",
        statusClass: "ok",
        messages: [
          { from: "customer", text: "What are your hours Sunday?" },
          { from: "assistant", text: "Sunday 11 AM to 5 PM. Anything you are after?", meta: "Auto · 15s" },
        ],
      },
    ],
    schedLabel: "Orders",
    schedTitle: "Orders & pickups this week",
    schedule: [
      [
        ["By 6 PM", "(604) 555-0148", "Hold · olive linen (M)", "Holding", "ok"],
        ["3:00 PM", "Pickup #3391", "Online order · ready", "Ready", "ok"],
        ["11:00 AM", "Erin C.", "Personal shopping", "Confirmed", "ok"],
      ],
      [
        ["2:00 PM", "Pickup #3402", "Online order", "Ready", "ok"],
        ["4:00 PM", "Restock", "Fall arrivals in store", "Note", "warn"],
      ],
      [["1:00 PM", "Pickup #3410", "Online order", "Ready", "ok"]],
      [],
      [
        ["11:00 AM", "VIP preview", "Early access · 12 invited", "Confirmed", "ok"],
        ["By 5 PM", "Pickup #3425", "Gift wrap requested", "Ready", "ok"],
      ],
      [["12:00 PM", "Pop-up table", "Sidewalk sale", "Confirmed", "ok"]],
      [],
    ],
    extraLabel: "Win-backs",
    extraTitle: "Customers to bring back",
    extra: [
      ["winback", "Lapsed 60+ days", "Win-back offer sent", "Sent", "ok"],
      ["campaign", "Fall drop campaign", "240 texted · 38 redeemed", "Live", "ok"],
      ["loyalty", "Loyal regular", "Eligible for VIP perk", "Queued", "ok"],
      ["review", "Recent buyer", "Review request sent", "Sent", "ok"],
    ],
    reviews: [
      {
        avatar: "E",
        name: "Erin C.",
        stars: 5,
        channel: "Google",
        when: "3h ago",
        text: "They held an item for me over text and it was waiting when I arrived. So easy.",
        draft: "Thank you, Erin! Holding it for you was our pleasure. See you next visit!",
      },
      {
        avatar: "T",
        name: "Tomas V.",
        stars: 5,
        channel: "Google",
        when: "2d ago",
        text: "Lovely shop, got a heads up when my size came back in.",
        draft: "Thanks, Tomas! We love giving regulars a heads up. See you soon!",
      },
      {
        avatar: "K",
        name: "Kira N.",
        stars: 4,
        channel: "Yelp",
        when: "5d ago",
        text: "Nice selection, would love more sizes in stock.",
        draft: "Thank you, Kira! We are expanding our size range and will text you when new stock lands.",
      },
    ],
  },
  dental: {
    business: "Cedar Dental",
    email: "demo@cedardental.ca",
    subtitle: "Here is everything happening across the clinic right now.",
    chips: [
      ["New patients", "7"],
      ["Recalls due", "41"],
      ["Avg response", "0:25"],
      ["Live now", "1"],
    ],
    live: {
      name: "(604) 555-0173",
      sub: "New patient · chipped tooth",
      line: '"...do you take new patients? I chipped a tooth."',
    },
    calls: [
      {
        icon: "phone",
        who: "(604) 555-0173",
        sub: "New patient · 2:14 PM",
        pill: "Exam booked",
        status: "ok",
        detail: "New patient with a chipped tooth. Platform booked a 10:40 exam and queued intake.",
      },
      {
        icon: "refill",
        who: "2:00 PM cancellation",
        sub: "Refilled · 1:30 PM",
        pill: "Refilled",
        status: "ok",
        detail: "A patient cancelled. Platform offered the chair to the waitlist and rebooked in 12 min.",
      },
      {
        icon: "recall",
        who: "Recall · 6 months",
        sub: "Reminder sent · 10:30 AM",
        pill: "Rebooked",
        status: "ok",
        detail: "Patient overdue for a cleaning. Platform sent a recall and they rebooked.",
      },
      {
        icon: "treatment",
        who: "Crown follow-up",
        sub: "Treatment nudge · 9:15 AM",
        pill: "Booked",
        status: "ok",
        detail: "Recommended treatment unbooked. A gentle nudge got it scheduled.",
      },
    ],
    convos: [
      {
        id: "d1",
        name: "(604) 555-0173",
        channel: "SMS",
        avatar: "#",
        last: "Yes please, thank you",
        time: "4m",
        status: "Booked",
        statusClass: "ok",
        messages: [
          { from: "customer", text: "Do you take new patients? I chipped a tooth." },
          {
            from: "assistant",
            text: "So sorry! Yes, we have an exam tomorrow 10:40 AM, book it?",
            meta: "Auto · 21s",
          },
          { from: "customer", text: "Yes please, thank you" },
          { from: "assistant", text: "Booked! Tomorrow 10:40 with Dr. Lee. Sending your form." },
        ],
      },
      {
        id: "d2",
        name: "Jordan T.",
        channel: "SMS",
        avatar: "J",
        last: "C",
        time: "1h",
        status: "Confirmed",
        statusClass: "ok",
        messages: [
          { from: "assistant", text: "Reminder: hygiene tomorrow 11 AM. Reply C." },
          { from: "customer", text: "C" },
          { from: "assistant", text: "Confirmed, see you then!" },
        ],
      },
      {
        id: "d3",
        name: "Priya K.",
        channel: "SMS",
        avatar: "P",
        last: "Let me check my calendar",
        time: "5h",
        status: "Needs you",
        statusClass: "warn",
        messages: [
          {
            from: "assistant",
            text: "Hi Priya, you are due for your 6-month cleaning. Openings next week, book one?",
          },
          { from: "customer", text: "Let me check my calendar" },
        ],
      },
    ],
    schedLabel: "Appointments",
    schedTitle: "Schedule this week",
    schedule: [
      [
        ["11:00 AM", "Hygiene · Vu", "Cleaning · 45 min", "Confirmed", "ok"],
        ["2:00 PM", "From waitlist", "Exam · refilled", "Refilled", "ok"],
        ["3:30 PM", "Recall · Lee", "Cleaning · rebooked", "Confirmed", "ok"],
      ],
      [
        ["10:40 AM", "New patient", "Exam · chipped tooth", "New", "new"],
        ["1:00 PM", "Crown · Okafor", "Treatment", "Confirmed", "ok"],
      ],
      [
        ["9:00 AM", "Hygiene · Tran", "Cleaning", "Confirmed", "ok"],
        ["11:30 AM", "Ortho consult", "New", "New", "new"],
      ],
      [],
      [
        ["8:30 AM", "Hygiene · Singh", "Cleaning", "Confirmed", "ok"],
        ["2:00 PM", "Filling · Diaz", "Treatment", "Confirmed", "ok"],
      ],
      [],
      [],
    ],
    extraLabel: "Recalls",
    extraTitle: "Patients due for recall",
    extra: [
      ["recall", "41 patients", "Overdue for 6-month cleaning", "28 reminded", "warn"],
      ["recall", "Priya K.", "Reminder sent · deciding", "Following up", "warn"],
      ["treatment", "Crown · recommended", "Treatment not yet booked", "Nudge sent", "warn"],
      ["recall", "Recall · rebooked", "Hygiene visit confirmed", "Booked", "ok"],
    ],
    reviews: [
      {
        avatar: "J",
        name: "Jordan T.",
        stars: 5,
        channel: "Google",
        when: "2h ago",
        text: "Got in same day for a chipped tooth as a new patient. Painless and friendly.",
        draft: "Thank you, Jordan! So glad we could see you quickly. Welcome to the practice!",
      },
      {
        avatar: "M",
        name: "Maya R.",
        stars: 5,
        channel: "Google",
        when: "2d ago",
        text: "The reminders are great, I never miss my cleanings now.",
        draft: "Thanks, Maya! Keeping you on track is exactly what we hoped for.",
      },
      {
        avatar: "S",
        name: "Sam D.",
        stars: 4,
        channel: "Google",
        when: "6d ago",
        text: "Good care, parking can be tricky but the team is wonderful.",
        draft: "Thank you, Sam! We will share parking tips ahead of your next visit.",
      },
    ],
  },
}

function buildAllIndustryData(session: ClientSession): ClientDashboardData {
  return {
    business: session.business,
    email: session.username.includes("@") ? session.username : `${session.username}@yourbusiness.com`,
    subtitle: "Here is everything happening across your business right now.",
    chips: [
      ["Calls today", "47"],
      ["Recovered by AI", "12"],
      ["Avg response", "0:23"],
      ["Live now", "1"],
    ],
    live: {
      name: "(604) 555-0148",
      sub: "New caller · Yaletown · inbound",
      line: '"...looking to book in sometime this week."',
    },
    calls: [
      {
        icon: "phone",
        who: "(604) 555-0148",
        sub: "New caller · 2:14 PM",
        pill: "Booked · +$340",
        status: "ok",
        detail: "Platform offered two times and booked the first, then sent a confirmation.",
      },
      {
        icon: "sms",
        who: "(778) 555-0192",
        sub: "Missed · texted back · 1:02 PM",
        pill: "Booked",
        status: "ok",
        detail: "Missed call texted back in 16s and booked.",
      },
      {
        icon: "phone",
        who: "Daniela R.",
        sub: "Inbound · 11:48 AM",
        pill: "Info given",
        status: "ok",
        detail: "Asked about hours and offered to book.",
      },
      {
        icon: "sms",
        who: "(236) 555-0177",
        sub: "Missed · texted back · 10:30 AM",
        pill: "Following up",
        status: "warn",
        detail: "Quote sent, platform follows up tomorrow.",
      },
    ],
    convos: [
      {
        id: "a1",
        name: "Sarah M.",
        channel: "SMS",
        avatar: "S",
        last: "Perfect, see you then!",
        time: "2m",
        status: "Booked",
        statusClass: "ok",
        messages: [
          { from: "customer", text: "Hi! Can I book in this week?" },
          { from: "assistant", text: "We have Thursday 2 PM, want me to book it?", meta: "Auto · 19s" },
          { from: "customer", text: "Yes please" },
          { from: "assistant", text: "Booked for Thursday 2 PM!" },
          { from: "customer", text: "Perfect, see you then!" },
        ],
      },
      {
        id: "a2",
        name: "Mike D.",
        channel: "Instagram",
        avatar: "M",
        last: "Any openings Saturday?",
        time: "18m",
        status: "AI replied",
        statusClass: "ok",
        messages: [
          { from: "customer", text: "Any openings Saturday?" },
          { from: "assistant", text: "Saturday 1:30 PM is open. Hold it?", meta: "Auto · 24s" },
        ],
      },
      {
        id: "a3",
        name: "Jordan T.",
        channel: "SMS",
        avatar: "J",
        last: "Thanks!",
        time: "3h",
        status: "Confirmed",
        statusClass: "ok",
        messages: [
          { from: "assistant", text: "Reminder: tomorrow at 2 PM. Reply C to confirm." },
          { from: "customer", text: "C" },
          { from: "assistant", text: "Confirmed!" },
          { from: "customer", text: "Thanks!" },
        ],
      },
    ],
    schedLabel: "Bookings",
    schedTitle: "Upcoming bookings",
    schedule: [
      [
        ["10:00 AM", "M. Reyes", "Consultation", "Confirmed", "ok"],
        ["2:00 PM", "Patel", "Booking · 2", "Confirmed", "ok"],
        ["4:30 PM", "Devon R.", "Booking", "Confirmed", "ok"],
      ],
      [
        ["11:00 AM", "Alexa G.", "Booking · 90 min", "Confirmed", "ok"],
        ["3:00 PM", "Mike D.", "Consultation", "Pending", "warn"],
      ],
      [["9:30 AM", "Okafor", "Booking", "Confirmed", "ok"]],
      [],
      [
        ["1:00 PM", "T. Nguyen", "Booking · 3", "Confirmed", "ok"],
        ["6:00 PM", "Lopez", "Booking · 8", "Confirmed", "ok"],
      ],
      [],
      [["12:00 PM", "Walk-in block", "Held by platform", "Held", "ok"]],
    ],
    extraLabel: "Follow-ups",
    extraTitle: "Pending follow-ups",
    extra: [
      ["followup", "(236) 555-0177", "Quote sent · awaiting reply", "Day 1", "warn"],
      ["followup", "Lapsed customer", "No visit in 45 days", "Win-back sent", "ok"],
      ["review", "Happy customer", "Review request queued", "Scheduled", "ok"],
      ["voicemail", "Voicemail", "Transcribed · needs callback", "New", "new"],
    ],
    reviews: [
      {
        avatar: "S",
        name: "Sarah K.",
        stars: 5,
        channel: "Google",
        when: "2h ago",
        text: "Fantastic experience start to finish. Will be back!",
        draft: "Thank you so much, Sarah! We cannot wait to welcome you back soon.",
      },
      {
        avatar: "D",
        name: "Dishan P.",
        stars: 4,
        channel: "Google",
        when: "1d ago",
        text: "Great service, short wait. Recommend.",
        draft: "Thanks, Dishan! We are always working on wait times and hope to see you again.",
      },
      {
        avatar: "M",
        name: "Marcus T.",
        stars: 5,
        channel: "Yelp",
        when: "2d ago",
        text: "Booking was so easy and the team was lovely.",
        draft: "Thank you, Marcus! Easy booking is exactly what we are going for.",
      },
    ],
  }
}

const DEFAULT_SESSION: ClientSession = {
  username: "demo",
  name: "Demo",
  business: "Your Business",
  since: 0,
}

export function getClientDashboardData(
  industry: DashboardIndustry,
  session: ClientSession = DEFAULT_SESSION,
): ClientDashboardData {
  if (industry === "all") return buildAllIndustryData(session)
  return BASE[industry]
}

export function listDashboardIndustries(): DashboardIndustry[] {
  return ["all", "restaurants", "salons", "trades", "retail", "dental"]
}
