import type { CalculatorConfig, CalculatorIndustry, CalculatorInputs } from "./types"

export const CALCULATOR_CONFIGS: Record<CalculatorIndustry, CalculatorConfig> = {
  dental: {
    industry: "dental",
    slug: "dental",
    path: "/tools/savings/dental",
    eyebrow: "Savings Estimator",
    headline: "What Are Your",
    headlineAccent: "Empty Chairs Worth?",
    subcopy:
      "Cancellations and no-shows leave chair time empty. See what the platform could recover by filling those slots from your waitlist.",
    resultsHeadline: "You could recover about",
    resultsSubcopy: "per year, from filled cancellations and empty slots",
    rowLabels: {
      monthly: "Recovered each month",
      count: "Appointments refilled / year",
      hours: "Chair-time recovered / year",
      profit: "Profit recovered / year",
    },
    fields: [
      {
        id: "practiceType",
        type: "select",
        label: "Practice type",
        defaultValue: "general",
        options: [
          { value: "general", label: "General Dentistry" },
          { value: "ortho", label: "Orthodontics" },
          { value: "cosmetic", label: "Cosmetic Dentistry" },
          { value: "pediatric", label: "Pediatric Dentistry" },
          { value: "perio", label: "Periodontics & Oral Surgery" },
        ],
      },
      {
        id: "locations",
        type: "number",
        label: "Number of locations",
        defaultValue: 1,
        min: 1,
        step: 1,
      },
      {
        id: "revenue",
        type: "number",
        label: "Average revenue per patient ($)",
        defaultValue: 300,
        min: 0,
        step: 10,
      },
      {
        id: "cancels",
        type: "number",
        label: "Cancellations & no-shows / week",
        defaultValue: 8,
        min: 0,
        step: 1,
      },
      {
        id: "empty",
        type: "number",
        label: "Open chair slots / week",
        defaultValue: 6,
        min: 0,
        step: 1,
      },
      {
        id: "refill",
        type: "range",
        label: "How much gets refilled",
        defaultValue: 65,
        min: 30,
        max: 90,
        step: 5,
        valueLabel: (v) => `${Math.round(v)}%`,
      },
      {
        id: "margin",
        type: "number",
        label: "Profit margin on a recovered visit (%)",
        defaultValue: 75,
        min: 0,
        max: 100,
        step: 5,
      },
    ],
    presets: {
      general: { revenue: 300, margin: 75 },
      ortho: { revenue: 5000, margin: 78 },
      cosmetic: { revenue: 3000, margin: 75 },
      pediatric: { revenue: 250, margin: 72 },
      perio: { revenue: 1500, margin: 68 },
    },
    hoursPerSlot: 0.75,
  },
  restaurants: {
    industry: "restaurants",
    slug: "restaurants",
    path: "/tools/savings/restaurants",
    eyebrow: "Savings Estimator",
    headline: "What Are Your",
    headlineAccent: "Empty Tables Worth?",
    subcopy:
      "Missed reservations and no-shows leave tables empty. See what the platform could recover by filling them from your waitlist.",
    resultsHeadline: "You could recover about",
    resultsSubcopy: "per year, from filled cancellations and empty tables",
    rowLabels: {
      monthly: "Recovered each month",
      count: "Covers refilled / year",
      hours: "Table-hours recovered / year",
      profit: "Profit recovered / year",
    },
    fields: [
      {
        id: "practiceType",
        type: "select",
        label: "Venue type",
        defaultValue: "casual",
        options: [
          { value: "casual", label: "Casual Dining" },
          { value: "fine", label: "Fine Dining" },
          { value: "cafe", label: "Café / Bakery" },
          { value: "bar", label: "Bar / Pub" },
          { value: "group", label: "Group / Chain" },
        ],
      },
      {
        id: "locations",
        type: "number",
        label: "Number of locations",
        defaultValue: 1,
        min: 1,
        step: 1,
      },
      {
        id: "revenue",
        type: "number",
        label: "Average cover value ($)",
        defaultValue: 120,
        min: 0,
        step: 5,
      },
      {
        id: "cancels",
        type: "number",
        label: "Cancellations & no-shows / week",
        defaultValue: 12,
        min: 0,
        step: 1,
      },
      {
        id: "empty",
        type: "number",
        label: "Empty tables / week",
        defaultValue: 8,
        min: 0,
        step: 1,
      },
      {
        id: "refill",
        type: "range",
        label: "How much gets refilled",
        defaultValue: 65,
        min: 30,
        max: 90,
        step: 5,
        valueLabel: (v) => `${Math.round(v)}%`,
      },
      {
        id: "margin",
        type: "number",
        label: "Profit margin per cover (%)",
        defaultValue: 60,
        min: 0,
        max: 100,
        step: 5,
      },
    ],
    presets: {
      casual: { revenue: 120, margin: 60 },
      fine: { revenue: 280, margin: 65 },
      cafe: { revenue: 55, margin: 62 },
      bar: { revenue: 95, margin: 70 },
      group: { revenue: 130, margin: 60 },
    },
    hoursPerSlot: 2.6,
  },
  salons: {
    industry: "salons",
    slug: "salons",
    path: "/tools/savings/salons",
    eyebrow: "Savings Estimator",
    headline: "What Are Your",
    headlineAccent: "Empty Chairs Worth?",
    subcopy:
      "Cancellations leave chairs empty. See what the platform could recover by filling those slots from your waitlist.",
    resultsHeadline: "You could recover about",
    resultsSubcopy: "per year, from filled cancellations and empty chairs",
    rowLabels: {
      monthly: "Recovered each month",
      count: "Appointments refilled / year",
      hours: "Chair-time recovered / year",
      profit: "Profit recovered / year",
    },
    fields: [
      {
        id: "practiceType",
        type: "select",
        label: "Salon type",
        defaultValue: "hair",
        options: [
          { value: "hair", label: "Hair Salon" },
          { value: "nails", label: "Nails" },
          { value: "spa", label: "Spa & Wellness" },
          { value: "barber", label: "Barbershop" },
          { value: "medspa", label: "Med Spa" },
        ],
      },
      {
        id: "locations",
        type: "number",
        label: "Number of locations",
        defaultValue: 1,
        min: 1,
        step: 1,
      },
      {
        id: "revenue",
        type: "number",
        label: "Average ticket ($)",
        defaultValue: 85,
        min: 0,
        step: 5,
      },
      {
        id: "cancels",
        type: "number",
        label: "Cancellations & no-shows / week",
        defaultValue: 10,
        min: 0,
        step: 1,
      },
      {
        id: "empty",
        type: "number",
        label: "Open chair slots / week",
        defaultValue: 6,
        min: 0,
        step: 1,
      },
      {
        id: "refill",
        type: "range",
        label: "How much gets refilled",
        defaultValue: 65,
        min: 30,
        max: 90,
        step: 5,
        valueLabel: (v) => `${Math.round(v)}%`,
      },
      {
        id: "margin",
        type: "number",
        label: "Profit margin per visit (%)",
        defaultValue: 55,
        min: 0,
        max: 100,
        step: 5,
      },
    ],
    presets: {
      hair: { revenue: 85, margin: 55 },
      nails: { revenue: 55, margin: 60 },
      spa: { revenue: 130, margin: 58 },
      barber: { revenue: 40, margin: 60 },
      medspa: { revenue: 260, margin: 65 },
    },
    hoursPerSlot: 1,
  },
  trades: {
    industry: "trades",
    slug: "trades",
    path: "/tools/savings/trades",
    eyebrow: "Savings Estimator",
    headline: "What Are Missed",
    headlineAccent: "Jobs Worth?",
    subcopy:
      "Missed calls and after-hours leads slip away on the job. See what the platform could book back onto your calendar.",
    resultsHeadline: "You could recover about",
    resultsSubcopy: "per year, from booked jobs you'd have missed",
    rowLabels: {
      monthly: "Recovered each month",
      count: "Jobs booked / year",
      hours: "On-site hours filled / year",
      profit: "Profit recovered / year",
    },
    fields: [
      {
        id: "practiceType",
        type: "select",
        label: "Trade type",
        defaultValue: "plumbing",
        options: [
          { value: "plumbing", label: "Plumbing" },
          { value: "hvac", label: "HVAC" },
          { value: "electrical", label: "Electrical" },
          { value: "roofing", label: "Roofing" },
          { value: "gc", label: "General Contracting" },
          { value: "landscaping", label: "Landscaping" },
        ],
      },
      {
        id: "locations",
        type: "number",
        label: "Number of crews",
        defaultValue: 1,
        min: 1,
        step: 1,
      },
      {
        id: "revenue",
        type: "number",
        label: "Average job value ($)",
        defaultValue: 450,
        min: 0,
        step: 50,
      },
      {
        id: "cancels",
        type: "number",
        label: "Missed calls / week",
        defaultValue: 15,
        min: 0,
        step: 1,
      },
      {
        id: "empty",
        type: "number",
        label: "After-hours calls / week",
        defaultValue: 6,
        min: 0,
        step: 1,
      },
      {
        id: "refill",
        type: "range",
        label: "How many turn into booked jobs",
        defaultValue: 45,
        min: 20,
        max: 90,
        step: 5,
        valueLabel: (v) => `${Math.round(v)}%`,
      },
      {
        id: "margin",
        type: "number",
        label: "Profit margin per job (%)",
        defaultValue: 45,
        min: 0,
        max: 100,
        step: 5,
      },
    ],
    presets: {
      plumbing: { revenue: 450, margin: 45 },
      hvac: { revenue: 650, margin: 42 },
      electrical: { revenue: 500, margin: 45 },
      roofing: { revenue: 4500, margin: 35 },
      gc: { revenue: 2800, margin: 32 },
      landscaping: { revenue: 600, margin: 45 },
    },
    hoursPerSlot: 2,
  },
  retail: {
    industry: "retail",
    slug: "retail",
    path: "/tools/savings/retail",
    eyebrow: "Savings Estimator",
    headline: "What Are Lost",
    headlineAccent: "Sales Worth?",
    subcopy:
      "Unanswered questions and lapsed buyers add up. See what the platform could recover by re-engaging customers automatically.",
    resultsHeadline: "You could recover about",
    resultsSubcopy: "per year, from recovered sales and win-backs",
    rowLabels: {
      monthly: "Recovered each month",
      count: "Sales recovered / year",
      hours: "Customer touches / year",
      profit: "Profit recovered / year",
    },
    fields: [
      {
        id: "practiceType",
        type: "select",
        label: "Store type",
        defaultValue: "boutique",
        options: [
          { value: "boutique", label: "Boutique" },
          { value: "specialty", label: "Specialty Retail" },
          { value: "home", label: "Home & Gift" },
          { value: "jewelry", label: "Jewelry" },
          { value: "group", label: "Multi-location" },
        ],
      },
      {
        id: "locations",
        type: "number",
        label: "Number of locations",
        defaultValue: 1,
        min: 1,
        step: 1,
      },
      {
        id: "revenue",
        type: "number",
        label: "Average basket ($)",
        defaultValue: 90,
        min: 0,
        step: 5,
      },
      {
        id: "cancels",
        type: "number",
        label: "Unanswered inquiries / week",
        defaultValue: 20,
        min: 0,
        step: 1,
      },
      {
        id: "empty",
        type: "number",
        label: "Lapsed buyers to win back / week",
        defaultValue: 8,
        min: 0,
        step: 1,
      },
      {
        id: "refill",
        type: "range",
        label: "How many convert to a sale",
        defaultValue: 55,
        min: 20,
        max: 90,
        step: 5,
        valueLabel: (v) => `${Math.round(v)}%`,
      },
      {
        id: "margin",
        type: "number",
        label: "Profit margin per sale (%)",
        defaultValue: 55,
        min: 0,
        max: 100,
        step: 5,
      },
    ],
    presets: {
      boutique: { revenue: 90, margin: 55 },
      specialty: { revenue: 120, margin: 50 },
      home: { revenue: 650, margin: 45 },
      jewelry: { revenue: 450, margin: 50 },
      group: { revenue: 110, margin: 52 },
    },
    hoursPerSlot: 1,
  },
}

export const CALCULATOR_SLUGS = Object.keys(CALCULATOR_CONFIGS) as CalculatorIndustry[]

export function getCalculatorConfig(slug: string): CalculatorConfig | undefined {
  return CALCULATOR_CONFIGS[slug as CalculatorIndustry]
}

export function getDefaultCalculatorInputs(config: CalculatorConfig): CalculatorInputs {
  const practiceField = config.fields.find(
    (f): f is Extract<CalculatorConfig["fields"][number], { type: "select" }> =>
      f.id === "practiceType" && f.type === "select",
  )
  const practiceType = practiceField?.defaultValue ?? Object.keys(config.presets)[0]
  const preset = config.presets[practiceType] ?? Object.values(config.presets)[0]

  const numDefault = (id: string, fallback: number): number => {
    const field = config.fields.find(
      (f): f is Extract<CalculatorConfig["fields"][number], { type: "number" }> =>
        f.id === id && f.type === "number",
    )
    return field?.defaultValue ?? fallback
  }
  const rangeDefault = (id: string, fallback: number): number => {
    const field = config.fields.find(
      (f): f is Extract<CalculatorConfig["fields"][number], { type: "range" }> =>
        f.id === id && f.type === "range",
    )
    return field?.defaultValue ?? fallback
  }

  return {
    practiceType,
    locations: numDefault("locations", 1),
    revenue: preset.revenue,
    cancels: numDefault("cancels", 0),
    empty: numDefault("empty", 0),
    refill: rangeDefault("refill", 65),
    margin: preset.margin,
  }
}
